image: node:latest

cache:
    paths:
        - node_modules/

stages:
    - build

build-job:
    stage: build
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    script:
        - npm ci
        - npm run build